linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
      - diagnostic
      - opinionated
    disabled-checks:
      - unnamedResult
      - hugeParam

linters:
  enable-all: true
  disable:
    - wsl
    - gomnd

service:
  golangci-lint-version: 1.23.x # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - GO111MODULE=on go mod vendor # required currently or golangci breaks

issues:
  exclude-use-default: false
  exclude-rules:
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - golint
